### ISSUE TITLE
CSS Houdini Implementation

### ISSUE THREAD

**Issue by tom2strobl** [tom2strobl/smooth-shadow#1]
An interesting idea came up today to leverage [CSS Houdini](https://developer.mozilla.org/en-US/docs/Web/Guide/Houdini) to enable a native CSS API like this:
```css
div {
  box-shadow: paint(smooth, 100, 0.5, 0.5);
}
```
I welcome anyone that is interested to take a stab at this.
